/**
 * Generated Scene Mode Page
 *
 * Generated by Design System Skill v1.0
 * Input: "生成情景模式页面（轮播 FeaturePromoCard + 条件开启列表 + 推荐开关）"
 * page_type: mobile-settings
 *
 * Needed components: status-bar, title-bar, feature-promo-card, list, list-item, switch
 */

"use client"

import { useState, useRef, type CSSProperties, type ReactNode } from "react"
import { StatusBar } from "@/component/StatusBar"
import { TitleBar } from "@/component/TitleBar"
import { List, ListItem } from "@/component/List"
import { Switch } from "@/component/Switch"
import { FeaturePromoCard } from "@/component/FeaturePromoCard"

import iconChevronBack from "@/blocks/assets/pixso-icons/icon-chevron-backward.png"
import iconArrowRightSmall from "@/blocks/assets/pixso-icons/icon-arrow-right-small.png"

const plusIcon =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
      <path d="M12 5V19M5 12H19" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
    </svg>`
  )

function MoonIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="scm-moon-bg" x1="12%" y1="6%" x2="92%" y2="100%">
          <stop offset="0%" stopColor="#B69CFF" />
          <stop offset="100%" stopColor="#7B5CFF" />
        </linearGradient>
        <linearGradient id="scm-moon-shape" x1="20%" y1="10%" x2="80%" y2="100%">
          <stop offset="0%" stopColor="#FFFFFF" stopOpacity="0.95" />
          <stop offset="100%" stopColor="#E2D6FF" stopOpacity="0.9" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#scm-moon-bg)" />
      <path
        d="M40.5 19c-.5 0-1 .03-1.5.08a14 14 0 0 0 6.4 23.43A15 15 0 1 1 40.5 19Z"
        fill="url(#scm-moon-shape)"
      />
      <circle cx="22" cy="20" r="1.5" fill="#FFFFFF" opacity="0.85" />
      <circle cx="48" cy="46" r="1.2" fill="#FFFFFF" opacity="0.7" />
      <circle cx="18" cy="44" r="1" fill="#FFFFFF" opacity="0.6" />
    </svg>
  )
}

function FocusIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="scm-focus-bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#FFD27A" />
          <stop offset="100%" stopColor="#FF8A4C" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#scm-focus-bg)" />
      <circle cx="32" cy="32" r="15" fill="none" stroke="#FFFFFF" strokeWidth="3.5" opacity="0.9" />
      <circle cx="32" cy="32" r="6" fill="#FFFFFF" />
    </svg>
  )
}

function SleepIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="scm-sleep-bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#7DD3FC" />
          <stop offset="100%" stopColor="#3B82F6" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#scm-sleep-bg)" />
      <text
        x="32"
        y="40"
        fontFamily="HarmonyOS Sans, -apple-system, sans-serif"
        fontSize="24"
        fontWeight="600"
        fill="#FFFFFF"
        textAnchor="middle"
      >
        Zz
      </text>
    </svg>
  )
}

type SceneCard = {
  id: string
  title: string
  subtitle: string
  icon: ReactNode
}

const sceneCards: SceneCard[] = [
  {
    id: "do-not-disturb",
    title: "免打扰",
    subtitle: "减少打扰保持专注",
    icon: <MoonIcon />,
  },
  {
    id: "focus",
    title: "专注模式",
    subtitle: "屏蔽通知 全心投入",
    icon: <FocusIcon />,
  },
  {
    id: "sleep",
    title: "睡眠模式",
    subtitle: "调暗屏幕 安然入睡",
    icon: <SleepIcon />,
  },
]

const CARD_W = 244
const CARD_GAP = 12
const TRACK_PADDING = 16

export default function SceneModePage() {
  const [activeIndex, setActiveIndex] = useState(0)
  const [recommendOn, setRecommendOn] = useState(false)
  const trackRef = useRef<HTMLDivElement>(null)

  const handleScroll = () => {
    const el = trackRef.current
    if (!el) return
    const idx = Math.round(el.scrollLeft / (CARD_W + CARD_GAP))
    if (idx !== activeIndex && idx >= 0 && idx < sceneCards.length) {
      setActiveIndex(idx)
    }
  }

  const conditionRowSubtitle = (
    <span style={{ color: "rgba(0,0,0,0.45)" }}>22:00 – 07:00 重复</span>
  )

  const recommendNote =
    "开启后，将结合时间、位置、APP 使用情况等信息，在合适的时候推荐开启或关闭模式。"

  const swiperStyle: CSSProperties = {
    scrollSnapType: "x mandatory",
    paddingLeft: TRACK_PADDING,
    paddingRight: TRACK_PADDING,
    scrollPaddingLeft: TRACK_PADDING,
    gap: `${CARD_GAP}px`,
  }

  return (
    <div
      className="w-[360px] mx-auto"
      style={{
        minHeight: "640px",
        background: "#F1F3F5",
      }}
    >
      <StatusBar time="22:08" backgroundColor="#F1F3F5" />

      <div className="px-4">
        <TitleBar
          title="情景模式"
          leftIcon={iconChevronBack}
          rightIcon={[plusIcon]}
          backgroundColor="#F1F3F5"
        />
      </div>

      {/* 模式卡片轮播：调用 FeaturePromoCard */}
      <div
        ref={trackRef}
        onScroll={handleScroll}
        className="flex overflow-x-auto pt-1 pb-2 hide-scrollbar"
        style={swiperStyle}
      >
        {sceneCards.map((card) => (
          <div
            key={card.id}
            className="shrink-0"
            style={{ scrollSnapAlign: "start" }}
          >
            <FeaturePromoCard
              icon={card.icon}
              title={card.title}
              subtitle={card.subtitle}
              actionLabel="立即开启"
              onAction={() => {}}
            />
          </div>
        ))}
      </div>

      {/* 指示器：命中当前导航位置 */}
      <div
        className="flex justify-center items-center gap-1.5 mt-3 mb-4"
        role="tablist"
        aria-label="情景模式分页"
      >
        {sceneCards.map((card, idx) => {
          const active = idx === activeIndex
          return (
            <span
              key={card.id}
              role="tab"
              aria-selected={active}
              aria-label={`第 ${idx + 1} 个模式`}
              style={{
                width: active ? 16 : 6,
                height: 6,
                borderRadius: 999,
                background: active ? "#0A59F7" : "rgba(0,0,0,0.18)",
                transition: "all 200ms ease",
              }}
            />
          )
        })}
      </div>

      {/* 条件开启 */}
      <div className="px-4">
        <div
          className="px-1 pb-2 text-[13px] font-medium"
          style={{ color: "rgba(0,0,0,0.55)" }}
        >
          条件开启
        </div>

        <div className="rounded-3xl overflow-hidden bg-white">
          <List>
            <ListItem
              title={<span className="font-medium">周日 周六</span>}
              subtitle={conditionRowSubtitle}
              right={
                <div className="flex items-center gap-1">
                  <span
                    className="text-[14px]"
                    style={{ color: "rgba(0,0,0,0.45)" }}
                  >
                    已关闭
                  </span>
                  <img
                    src={iconArrowRightSmall}
                    alt=""
                    className="w-3 h-6 ml-0.5"
                  />
                </div>
              }
              showArrow={false}
              onClick={() => {}}
            />

            <ListItem
              title={
                <span className="font-medium" style={{ color: "#0A59F7" }}>
                  + 添加条件
                </span>
              }
              showArrow={false}
              border={false}
              onClick={() => {}}
            />
          </List>
        </div>
      </div>

      {/* 推荐开启与关闭 */}
      <div className="px-4 mt-4 pb-6">
        <div className="rounded-3xl overflow-hidden bg-white">
          <List>
            <ListItem
              title={<span className="font-medium">推荐开启与关闭</span>}
              right={
                <Switch
                  modelValue={recommendOn}
                  onUpdateModelValue={setRecommendOn}
                />
              }
              showArrow={false}
              border={false}
            />
          </List>
        </div>

        <p
          className="px-2 pt-3 text-[12px] leading-relaxed"
          style={{ color: "rgba(0,0,0,0.45)" }}
        >
          {recommendNote}
        </p>
      </div>

      <div className="h-7 flex justify-center items-end pb-1">
        <div className="w-28 h-1.5 rounded-full bg-black/25"></div>
      </div>

      <style>{`
        .hide-scrollbar::-webkit-scrollbar { display: none; }
        .hide-scrollbar { scrollbar-width: none; -ms-overflow-style: none; }
      `}</style>
    </div>
  )
}
