/**
 * Scenario Mode Page V1
 *
 * Generated by Design System Skill v1.0
 * Input: 二级设置页 — 情景模式（标题栏 3 图标 + 说明 + 轮播 FeaturePromoCard + 条件开启 + 推荐开关）
 *
 * Needed components: status-bar, title-bar, feature-promo-card, list, list-item, divider, switch
 */

"use client"

import { useState, useRef, type CSSProperties, type ReactNode } from "react"
import { StatusBar } from "@/component/StatusBar"
import { TitleBar } from "@/component/TitleBar"
import { List, ListItem } from "@/component/List"
import { Divider } from "@/component/Divider"
import { Switch } from "@/component/Switch"
import { FeaturePromoCard } from "@/component/FeaturePromoCard"

import iconChevronBack from "@/blocks/assets/pixso-icons/icon-chevron-backward.png"
import iconArrowRightSmall from "@/blocks/assets/pixso-icons/icon-arrow-right-small.png"

const HIGHLIGHT_BLUE = "#0A59F7"

const inlineSvg = (svg: string) =>
  "data:image/svg+xml;utf8," + encodeURIComponent(svg)

const iconAdd = inlineSvg(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M12 5V19M5 12H19" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  </svg>`
)

const iconHelp = inlineSvg(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <circle cx="12" cy="12" r="9" stroke="#000000" stroke-width="2" />
    <path d="M9.5 9.5C9.5 8.12 10.62 7 12 7C13.38 7 14.5 8.12 14.5 9.5C14.5 10.5 14 11 13 11.5C12.3 11.85 12 12.3 12 13.2V13.5" stroke="#000000" stroke-width="2" stroke-linecap="round" />
    <circle cx="12" cy="16.8" r="1.05" fill="#000000" />
  </svg>`
)

const iconMore = inlineSvg(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <circle cx="6" cy="12" r="1.8" fill="#000000" />
    <circle cx="12" cy="12" r="1.8" fill="#000000" />
    <circle cx="18" cy="12" r="1.8" fill="#000000" />
  </svg>`
)

function TimeListIcon() {
  return (
    <div
      className="w-9 h-9 rounded-full flex items-center justify-center shrink-0"
      style={{ background: "rgba(10, 89, 247, 0.08)" }}
      aria-hidden="true"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="12" cy="12" r="9" stroke={HIGHLIGHT_BLUE} strokeWidth="1.8" />
        <path d="M12 7.5V12L15 14" stroke={HIGHLIGHT_BLUE} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </div>
  )
}

function MoonIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="smv1-moon-bg" x1="12%" y1="6%" x2="92%" y2="100%">
          <stop offset="0%" stopColor="#B69CFF" />
          <stop offset="100%" stopColor="#7B5CFF" />
        </linearGradient>
        <linearGradient id="smv1-moon-shape" x1="20%" y1="10%" x2="80%" y2="100%">
          <stop offset="0%" stopColor="#FFFFFF" stopOpacity="0.95" />
          <stop offset="100%" stopColor="#E2D6FF" stopOpacity="0.9" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#smv1-moon-bg)" />
      <path
        d="M40.5 19c-.5 0-1 .03-1.5.08a14 14 0 0 0 6.4 23.43A15 15 0 1 1 40.5 19Z"
        fill="url(#smv1-moon-shape)"
      />
      <circle cx="22" cy="20" r="1.5" fill="#FFFFFF" opacity="0.85" />
      <circle cx="48" cy="46" r="1.2" fill="#FFFFFF" opacity="0.7" />
      <circle cx="18" cy="44" r="1" fill="#FFFFFF" opacity="0.6" />
    </svg>
  )
}

function FocusIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="smv1-focus-bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#FFD27A" />
          <stop offset="100%" stopColor="#FF8A4C" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#smv1-focus-bg)" />
      <circle cx="32" cy="32" r="15" fill="none" stroke="#FFFFFF" strokeWidth="3.5" opacity="0.9" />
      <circle cx="32" cy="32" r="6" fill="#FFFFFF" />
    </svg>
  )
}

function SleepIcon() {
  return (
    <svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="smv1-sleep-bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#7DD3FC" />
          <stop offset="100%" stopColor="#3B82F6" />
        </linearGradient>
      </defs>
      <circle cx="32" cy="32" r="30" fill="url(#smv1-sleep-bg)" />
      <text
        x="32"
        y="40"
        fontFamily="HarmonyOS Sans, -apple-system, sans-serif"
        fontSize="24"
        fontWeight="600"
        fill="#FFFFFF"
        textAnchor="middle"
      >
        Zz
      </text>
    </svg>
  )
}

type SceneCard = {
  id: string
  title: string
  subtitle: string
  icon: ReactNode
}

const sceneCards: SceneCard[] = [
  {
    id: "do-not-disturb",
    title: "免打扰",
    subtitle: "减少打扰保持专注",
    icon: <MoonIcon />,
  },
  {
    id: "focus",
    title: "专注模式",
    subtitle: "屏蔽通知 全心投入",
    icon: <FocusIcon />,
  },
  {
    id: "sleep",
    title: "睡眠模式",
    subtitle: "调暗屏幕 安然入睡",
    icon: <SleepIcon />,
  },
]

const CARD_W = 244
const CARD_GAP = 12
const TRACK_PADDING = 16

function GroupLabel({ children }: { children: ReactNode }) {
  return (
    <div
      className="px-1 pb-2 text-[13px] font-medium"
      style={{ color: "rgba(0,0,0,0.55)" }}
    >
      {children}
    </div>
  )
}

function GroupNote({ children }: { children: ReactNode }) {
  return (
    <p
      className="px-2 pt-3 text-[12px] leading-relaxed"
      style={{ color: "rgba(0,0,0,0.45)" }}
    >
      {children}
    </p>
  )
}

export default function ScenarioModePageV1() {
  const [activeIndex, setActiveIndex] = useState(0)
  const [recommendOn, setRecommendOn] = useState(true)
  const trackRef = useRef<HTMLDivElement>(null)

  const handleScroll = () => {
    const el = trackRef.current
    if (!el) return
    const idx = Math.round(el.scrollLeft / (CARD_W + CARD_GAP))
    if (idx !== activeIndex && idx >= 0 && idx < sceneCards.length) {
      setActiveIndex(idx)
    }
  }

  const swiperStyle: CSSProperties = {
    scrollSnapType: "x mandatory",
    paddingLeft: TRACK_PADDING,
    paddingRight: TRACK_PADDING,
    scrollPaddingLeft: TRACK_PADDING,
    gap: `${CARD_GAP}px`,
  }

  return (
    <div
      className="w-[360px] mx-auto"
      style={{
        minHeight: "640px",
        background: "#F1F3F5",
      }}
    >
      <StatusBar time="22:08" backgroundColor="#F1F3F5" />

      {/* 标题栏：左返回 + 标题 + 右三图标（新增 / 问号 / 更多） */}
      <div className="px-4">
        <TitleBar
          title="情景模式"
          leftIcon={iconChevronBack}
          rightIcons={[iconAdd, iconHelp, iconMore]}
          backgroundColor="#F1F3F5"
        />
      </div>

      {/* 标题栏下方说明文字 */}
      <p
        className="px-5 pt-1 pb-3 text-[13px] leading-5"
        style={{ color: "rgba(0,0,0,0.55)" }}
      >
        开启后会自动调整系统功能，让您能全身心投入情景。
      </p>

      {/* 二楼：可滑动情景卡片（FeaturePromoCard） */}
      <div
        ref={trackRef}
        onScroll={handleScroll}
        className="flex overflow-x-auto pt-1 pb-2 hide-scrollbar"
        style={swiperStyle}
      >
        {sceneCards.map((card) => (
          <div
            key={card.id}
            className="shrink-0"
            style={{ scrollSnapAlign: "start" }}
          >
            <FeaturePromoCard
              icon={card.icon}
              title={card.title}
              subtitle={card.subtitle}
              actionLabel="立即开启"
              onAction={() => {}}
            />
          </div>
        ))}
      </div>

      {/* 卡片下方紧挨导航点 */}
      <div
        className="flex justify-center items-center gap-1.5 mt-2 mb-5"
        role="tablist"
        aria-label="情景模式分页"
      >
        {sceneCards.map((card, idx) => {
          const active = idx === activeIndex
          return (
            <span
              key={card.id}
              role="tab"
              aria-selected={active}
              aria-label={`第 ${idx + 1} 个模式`}
              style={{
                width: active ? 16 : 6,
                height: 6,
                borderRadius: 999,
                background: active ? HIGHLIGHT_BLUE : "rgba(0,0,0,0.18)",
                transition: "all 200ms ease",
              }}
            />
          )
        })}
      </div>

      {/* 二楼：条件开启 list 卡片 */}
      <div className="px-4">
        <GroupLabel>条件开启</GroupLabel>

        <div className="rounded-3xl overflow-hidden bg-white">
          <ListItem
            left={<TimeListIcon />}
            title={<span className="font-medium">周日 周六</span>}
            subtitle={
              <span style={{ color: "rgba(0,0,0,0.45)" }}>
                22:00 - 次日 07:00
              </span>
            }
            right={
              <div className="flex items-center gap-1">
                <span
                  className="text-[14px]"
                  style={{ color: "rgba(0,0,0,0.45)" }}
                >
                  已关闭
                </span>
                <img
                  src={iconArrowRightSmall}
                  alt=""
                  className="w-3 h-6 ml-0.5"
                />
              </div>
            }
            border={false}
            showArrow={false}
            onClick={() => {}}
          />

          <div className="px-4">
            <Divider hairline margin="0" />
          </div>

          <button
            type="button"
            className="w-full text-left px-4 py-3.5 text-[15px] font-medium"
            style={{ color: HIGHLIGHT_BLUE }}
            onClick={() => {}}
          >
            添加条件
          </button>
        </div>

        <GroupNote>本功能需调用位置权限，读取位置信息。</GroupNote>
      </div>

      {/* 三楼：推荐开启与关闭 */}
      <div className="px-4 mt-4 pb-6">
        <div className="rounded-3xl overflow-hidden bg-white">
          <List>
            <ListItem
              title={<span className="font-medium">推荐开启与关闭</span>}
              right={
                <Switch
                  modelValue={recommendOn}
                  onUpdateModelValue={setRecommendOn}
                />
              }
              showArrow={false}
              border={false}
            />
          </List>
        </div>

        <GroupNote>
          基于个人偏好，以及位置、时间等数据信息，智能推荐开启或关闭相应的情景模式，关闭后将影响情景模式的推荐体验。
        </GroupNote>
      </div>

      <div className="h-7 flex justify-center items-end pb-1">
        <div className="w-28 h-1.5 rounded-full bg-black/25"></div>
      </div>

      <style>{`
        .hide-scrollbar::-webkit-scrollbar { display: none; }
        .hide-scrollbar { scrollbar-width: none; -ms-overflow-style: none; }
      `}</style>
    </div>
  )
}
