/**
 * Generated Water Settings Page - Stories
 *
 * Generated by Design System Skill v1.0
 */

import type { Meta, StoryObj } from "@storybook/react-vite"
import WaterSettingsGeneratedPage from "./index"

const meta = {
  title: "Render/WaterSettingsGenerated",
  component: WaterSettingsGeneratedPage,
  tags: ["autodocs"],
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof WaterSettingsGeneratedPage>

export default meta

type Story = StoryObj<typeof meta>

export const Default: Story = {
  render: () => (
    <div style={{ width: "360px", minHeight: "800px", margin: "0 auto" }}>
      <WaterSettingsGeneratedPage />
    </div>
  ),
}
