/**
 * Generated Water Settings Page
 *
 * Generated by Design System Skill v1.0
 * Input: "生成一个喝水设置页"
 * page_type: mobile-settings
 * layout: .resources/harmony/layout/mobile-settings.md
 *
 * Reference blocks: water-settings, settings-page
 * Needed components: status-bar, title-bar, list, list-item, switch, divider
 */

"use client"

import { useState } from "react"
import { StatusBar } from "@/component/StatusBar"
import { TitleBar } from "@/component/TitleBar"
import { List, ListItem } from "@/component/List"
import { Switch } from "@/component/Switch"

export default function WaterSettingsGeneratedPage() {
  const [remindEnabled, setRemindEnabled] = useState(true)

  const textTitle = "喝水设置"
  const textGoal = "目标设定"
  const textReminder = "提醒"
  const textStartTime = "提醒开始时间"
  const textEndTime = "提醒结束时间"
  const textReminderNote = "默认每小时提醒一次。为避免打扰，\"每日喝水\"会在您设置的提醒范围内根据打卡的进度灵活提醒，且12:00~14:00时段午休时间，不进行提醒。"

  return (
    <div className="w-[360px] min-h-[792px] mx-auto bg-background-secondary">
      {/* Shell: Status Bar */}
      <StatusBar
        mode="light"
        time="08:08"
        backgroundColor="#f1f3f5"
      />

      {/* Shell: TitleBar */}
      <div className="w-[328px] mx-auto">
        <TitleBar
          variant="secondary"
          title={textTitle}
          style={{ backgroundColor: "#f1f3f5" }}
        />
      </div>

      {/* Content Region */}
      <div className="px-4">
        {/* Entry Card: 目标设定 */}
        <List className="rounded-3xl bg-comp-background-primary">
          <ListItem
            title={<span className="font-medium">{textGoal}</span>}
            right={
              <div className="flex items-center gap-1">
                <span className="text-font-secondary">2000 ml</span>
                <svg width="8" height="14" viewBox="0 0 8 14" fill="none" className="text-icon-secondary">
                  <path d="M1 1L7 7L1 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                </svg>
              </div>
            }
            showArrow={false}
            border={false}
            onClick={() => {}}
          />
        </List>

        {/* Group Card: 提醒设置 */}
        <div className="mt-2 rounded-3xl overflow-hidden bg-comp-background-primary">
          <List>
            <ListItem
              title={<span className="font-medium">{textReminder}</span>}
              right={
                <Switch
                  modelValue={remindEnabled}
                  onUpdateModelValue={setRemindEnabled}
                />
              }
              showArrow={false}
              border={false}
            />

            <ListItem
              title={textStartTime}
              right={
                <div className="flex items-center gap-1">
                  <span className="text-font-secondary pl-3">08:00</span>
                  <svg width="8" height="14" viewBox="0 0 8 14" fill="none" className="text-icon-secondary">
                    <path d="M1 1L7 7L1 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                  </svg>
                </div>
              }
              showArrow={false}
              border={false}
              onClick={() => {}}
            />

            <ListItem
              title={textEndTime}
              right={
                <div className="flex items-center gap-1">
                  <span className="text-font-secondary pl-3">18:00</span>
                  <svg width="8" height="14" viewBox="0 0 8 14" fill="none" className="text-icon-secondary">
                    <path d="M1 1L7 7L1 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                  </svg>
                </div>
              }
              showArrow={false}
              border={false}
              onClick={() => {}}
            />
          </List>
        </div>

        {/* Informational Note */}
        <p className="text-xs text-font-secondary mt-2 leading-relaxed">
          {textReminderNote}
        </p>
      </div>

      {/* Shell: Home Indicator */}
      <div className="h-7 flex justify-center">
        <div className="w-28 h-1.5 rounded-full bg-gray-300"></div>
      </div>
    </div>
  )
}
